spring:
  application:
    name: RetirementCalculatorBackend
  ai:
    retry:
      max-attempts: 1
      exclude-on-http-codes: 429
    openai:
      chat:
        options:
          model: ${AI_MODEL}
      base-url: ${AI_BASE_URL}
      api-key: ${AI_KEY}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: ${JWT_EXPIRATION}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    enabled: true

server:
  port: 8080
